"""Shared inference service. Only load model artifacts generated by this project."""
import json
import logging
import threading
from functools import lru_cache
from pathlib import Path
import joblib
import numpy as np
import pandas as pd
from sklearn.neighbors import NearestNeighbors
from src.features import FEATURE_ORDER, FEATURES, NUMERIC
from backend.sevices.recommendations import RULE_VERSION, generate_recommendations

ROOT=Path(__file__).resolve().parents[1]
logger=logging.getLogger(__name__)
DISCLAIMER="Educational research prototype. Estimates the dataset disease-presence label, not diagnosis, disease severity, or future events."

class InferenceEngine:
    def __init__(self):
        pointer=ROOT/"models/active.json"
        if not pointer.exists(): raise RuntimeError("No active model. Run: python -m src.train_model")
        version=json.loads(pointer.read_text())["version"]
        if Path(version).name != version: raise RuntimeError("Invalid model pointer")
        self.bundle=joblib.load(ROOT/"models/versions"/version/"bundle.joblib")
        self.model=self.bundle["model"];self.report=self.bundle["report"];self.version=version
        self.training=self.bundle["train_X"];self.explain_lock=threading.Lock()
        # Support checks must use the same active pipeline as prediction and
        # explanation, rather than whichever candidate was serialized first.
        self.preprocessor=self.model.named_steps["preprocess"]
        encoded=self.preprocessor.transform(self.training)
        self.neighbors=NearestNeighbors(n_neighbors=4).fit(encoded)
        self.distance_limit=float(np.quantile(self.neighbors.kneighbors(encoded,n_neighbors=2)[0][:,1],.95))
        self.explainer=None

    @staticmethod
    def risk_level(probability: float) -> str:
        """Return the documented display band without changing prediction threshold."""
        return "LOW" if probability < .3 else "MEDIUM" if probability < .7 else "HIGH"

    def frame(self,data): return pd.DataFrame([data],columns=FEATURE_ORDER)
    def probability(self,values):
        return self.model.predict_proba(pd.DataFrame(values,columns=FEATURE_ORDER))[:,list(self.model.classes_).index(1)]
    @lru_cache(maxsize=256)
    def explain(self,model_version,values):
        """Return a personal, probability-space explanation for one input snapshot.

        The model version and complete ordered values are explicit cache inputs.
        This prevents a future engine/version change from reusing an attribution
        for a different deployed artifact or assessment.
        """
        if model_version != self.version:
            raise ValueError("Explanation model version does not match the active model")
        import shap
        frame=pd.DataFrame([values],columns=FEATURE_ORDER)
        with self.explain_lock:
            if self.explainer is None:
                self.explainer=shap.PermutationExplainer(self.probability,self.bundle["background"],feature_names=FEATURE_ORDER,seed=42)
            explanation=self.explainer(frame,max_evals=135,silent=True)
        contributions=np.asarray(explanation.values[0],dtype=float)
        base=float(np.asarray(explanation.base_values).reshape(-1)[0])
        output=float(self.probability(frame)[0])
        residual=output-base-float(contributions.sum())
        if abs(residual)>1e-5: raise ValueError("SHAP reconstruction failed")
        factors=[dict(feature=k,label=FEATURES[k]["label"],patient_value=float(values[i]),
                      shap_contribution=float(contributions[i]),contribution_pp=float(contributions[i]*100)) for i,k in enumerate(FEATURE_ORDER)]
        return {"status":"available","method":"Permutation SHAP (5 permutations, 32 training reference rows)",
                "units":"probability","base_value":base,"output_value":output,"reconstruction_error":residual,
                "factors":factors,"note":"Approximate model attribution relative to training reference data; not causal effects."}

    def assess(self,data,explain=True):
        frame=self.frame(data);p=float(self.probability(frame)[0])
        comparisons=[]
        for name,model in self.bundle["candidates"].items():
            prob=float(model.predict_proba(frame)[0,1])
            comparisons.append({"model":name,"probability":prob,"prediction":int(prob>=.5)})
        probabilities=[m["probability"] for m in comparisons]
        level=self.risk_level(p)
        encoded=self.preprocessor.transform(frame)
        distances,indices=self.neighbors.kneighbors(encoded,n_neighbors=3)
        unusual=[]
        for key in NUMERIC:
            stats=self.report["feature_statistics"][key]
            if data[key]<stats["min"] or data[key]>stats["max"]:
                unusual.append({"feature":key,"value":data[key],"training_min":stats["min"],"training_max":stats["max"]})
        distance=float(distances[0,0])
        explanation={"status":"not_requested","factors":[]}
        if explain:
            try: explanation=self.explain(self.version,tuple(data[k] for k in FEATURE_ORDER))
            except Exception:
                logger.exception("SHAP calculation failed")
                explanation={"status":"unavailable","factors":[],"note":"Explanation temporarily unavailable. Prediction succeeded, but its SHAP explanation could not be computed."}
        factors=explanation["factors"]
        result={"model_version":self.version,"selected_model":self.report["selected_model"],"calibrated":self.report["calibrated"],
          "features":data,"probability":p,"prediction_value":int(p>=.5),
          "prediction":"Model positive" if p>=.5 else "Model negative","risk_level":level,
          "risk_summary":{"score":round(p*100,2),"level":level},
          "early_warning":"Score bands are exploratory display categories, not clinical urgency levels.",
          "explanation":explanation,"explainability_status":explanation["status"],
          "factors_increasing_risk":sorted([x for x in factors if x["shap_contribution"]>0],key=lambda x:-x["shap_contribution"]),
          "factors_decreasing_risk":sorted([x for x in factors if x["shap_contribution"]<0],key=lambda x:x["shap_contribution"]),
          "model_comparison":comparisons,
          "disagreement":{"class_disagreement":len({m["prediction"] for m in comparisons})>1,
                           "probability_spread":max(probabilities)-min(probabilities),
                           "note":"Candidate disagreement at threshold 0.5; agreement does not establish correctness or confidence."},
          "input_support":{"status":"available","flagged":bool(unusual) or distance>self.distance_limit,"outside_training_range":unusual,
                           "nearest_distance":distance,"training_distance_95":self.distance_limit,
                           "note":"Heuristic distance in standardized and one-hot encoded training space; not a validated uncertainty estimate."},
          "similar_cases":[{"reference":f"Training reference {int(j)+1:03d}","distance":float(d),
                            "features":{k:float(v) for k,v in self.training.iloc[j].items()},
                            "recorded_label":int(self.bundle["train_y"].iloc[j])} for d,j in zip(distances[0],indices[0])],
          "recommendations":generate_recommendations(data),
          "recommendation_rule_version":RULE_VERSION,
          "disclaimer":DISCLAIMER}
        return result

    @lru_cache(maxsize=1)
    def global_shap(self):
        sample=self.training.sample(min(24,len(self.training)),random_state=42)
        values=[self.explain(self.version,tuple(row[k] for k in FEATURE_ORDER)) for _,row in sample.iterrows()]
        factors=[{"feature":k,"label":FEATURES[k]["label"],"mean_absolute_contribution":float(np.mean([abs(e["factors"][i]["shap_contribution"]) for e in values]))} for i,k in enumerate(FEATURE_ORDER)]
        return {"model_version":self.version,"n":len(sample),"population":"Fixed training sample (not test data)","factors":sorted(factors,key=lambda x:-x["mean_absolute_contribution"])}
