import pandas as pd
import joblib
from pathlib import Path


# ==========================================
# 1. Define project paths
# ==========================================

BASE_DIR = Path(__file__).resolve().parent.parent

MODEL_FILE = BASE_DIR / "models" / "best_model.pkl"


# ==========================================
# 2. Load trained model
# ==========================================

model = joblib.load(MODEL_FILE)

print("=" * 60)
print("HEALTHCARE HEART DISEASE RISK PREDICTION SYSTEM")
print("=" * 60)


# ==========================================
# 3. Get patient information
# ==========================================

print("\nEnter Patient Information")

age = float(input("Age: "))

sex = float(input(
    "Sex (1 = Male, 0 = Female): "
))

cp = float(input(
    "Chest Pain Type (0-3): "
))

trestbps = float(input(
    "Resting Blood Pressure: "
))

chol = float(input(
    "Cholesterol: "
))

fbs = float(input(
    "Fasting Blood Sugar > 120 mg/dl (1 = Yes, 0 = No): "
))

restecg = float(input(
    "Resting ECG Results (0-2): "
))

thalach = float(input(
    "Maximum Heart Rate Achieved: "
))

exang = float(input(
    "Exercise-Induced Angina (1 = Yes, 0 = No): "
))

oldpeak = float(input(
    "ST Depression (Oldpeak): "
))

slope = float(input(
    "Slope of Peak Exercise ST Segment (0-2): "
))

ca = float(input(
    "Number of Major Vessels (0-3): "
))

thal = float(input(
    "Thalassemia (1-3): "
))


# ==========================================
# 4. Create patient data
# ==========================================

patient_data = pd.DataFrame([{

    "age": age,

    "sex": sex,

    "cp": cp,

    "trestbps": trestbps,

    "chol": chol,

    "fbs": fbs,

    "restecg": restecg,

    "thalach": thalach,

    "exang": exang,

    "oldpeak": oldpeak,

    "slope": slope,

    "ca": ca,

    "thal": thal

}])


# ==========================================
# 5. Make prediction
# ==========================================

prediction = model.predict(patient_data)[0]

probability = model.predict_proba(
    patient_data
)[0][1]


# ==========================================
# 6. Determine risk level
# ==========================================

if probability < 0.30:

    risk_level = "LOW"

elif probability < 0.70:

    risk_level = "MEDIUM"

else:

    risk_level = "HIGH"


# ==========================================
# 7. Display prediction
# ==========================================

print("\n" + "=" * 60)
print("PREDICTION RESULT")
print("=" * 60)


if prediction == 1:

    print("Prediction: HEART DISEASE PRESENT")

else:

    print("Prediction: NO HEART DISEASE")


print(
    f"Risk Probability: {probability * 100:.2f}%"
)

print(
    f"Risk Level: {risk_level}"
)


print("\n" + "=" * 60)
print("IMPORTANT")
print("=" * 60)

print(
    "This prediction is generated by a machine learning model "
    "and should not be considered a medical diagnosis."
)